# Generated by Django 4.1.4 on 2022-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment_status_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
